image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'
  - name: alias
    command: echo 'alias run="python3 /workspace/django_todo/manage.py runserver 0.0.0.0:8080"' >> ~/.bashrc && source ~/.bashrc

export DEVELOPMENT=1